### ISSUE TITLE
Make Compatible with macOS.

### ISSUE THREAD

**Issue by LefterisJP** [refu-lang/refu#27]
I have not tried to build refu in macOS so I can't confirm yet whether or not it is possible out of the box. Possibly requires a bit of adjustment. This issue is to track:

- [ ] Make necessary code changes to allow for compilation in macOS.
- [ ] Make appropriate entries in the readme with a guide how to compile in macOS.

**Comment by axic** [comment]
It doesn't work because of at least these issues:
- the io library doesn't support it (f* operations are 64 bit by default, and there are no `..o64` counterparts)
- the system library doesn't support Mac
- the IR token table (rirtoken) isn't generated by gpref and manually generating it creates a conflicting output

That's where I gave up.

**Comment by LefterisJP** [comment]
Should be addressed with #37 and https://github.com/refu-lang/refu/commit/69dbb7ab02a306bbcb4c71c54c48393a269ea2b2
